// This file is auto-generated by cmake

#pragma once

namespace opossum {

// We need this file to store the current GIT hash and make it available to our binaries.

// The SHA1 for the HEAD of the repo.
#define GIT_HEAD_SHA1 "58b0ba21700cb9b787c4565e559a05d765a30ab3"

// Whether or not there were uncommitted changes present.
#define GIT_IS_DIRTY true

}  // namespace opossum
