FIND_PATH(LIBPMEM2_INCLUDE_DIR NAME libpmem2.h
    HINTS /usr/include /scratch/pmdk1.10/include/ /scratch/pmem/pmdk1.10/include/
    NO_DEFAULT_PATH NO_CMAKE_ENVIRONMENT_PATH NO_CMAKE_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_SYSTEM_PATH 
)

FIND_LIBRARY(LIBPMEM2_LIBRARY NAME pmem2
    HINTS /usr/lib/ /scratch/pmdk1.10/lib/ /scratch/pmem/pmdk1.10/lib/
    NO_DEFAULT_PATH NO_CMAKE_ENVIRONMENT_PATH NO_CMAKE_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_SYSTEM_PATH 
    )

	IF (LIBPMEM2_INCLUDE_DIR)
	MESSAGE(STATUS "Found include")
	ENDIF ()
	IF (LIBPMEM2_LIBRARY)
	MESSAGE(STATUS "Found lib")

	ENDIF()

IF (LIBPMEM2_INCLUDE_DIR AND LIBPMEM2_LIBRARY)
    SET(LIBPMEM2_FOUND TRUE)
    MESSAGE(STATUS "Found libpmem2 library: inc=${LIBPMEM2_INCLUDE_DIR}, lib=${LIBPMEM2_LIBRARY}")
ELSE ()
    SET(LIBPMEM2_FOUND FALSE)
    MESSAGE(STATUS "WARNING: libpmem2 library not found.")
ENDIF ()
